#!/bin/bash
#
# Bump the docs sources to a new openzeppelin-solidity release.
# The changes are pushed to the openzeppelin-docs repository.
# Argument:
#   version: the version of the new release.

set -ev

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

readonly VERSION="$1"

# bump-docs will fail if the version is already generated.
npm run bump-docs -- "${VERSION}"

# Push the updated docs sources to the openzeppelin-docs repository.
git config user.name "openzeppelin-lurch"
git config user.email "lurch@openzeppelin.org"
git add .
git commit -m "Bump the docs to version ${VERSION}"
git push "https://${GH_TOKEN}@github.com/OpenZeppelin/openzeppelin-docs.git" HEAD:master
